### ISSUE TITLE
Facebook login is always blocked before it can scrape data

### ISSUE THREAD

**Issue by zchryy03** [AbderrahimAl/Facebook-Scraper#2]
https://www.facebook.com/checkpoint/block/

![image](https://user-images.githubusercontent.com/52731972/133088327-c31f9c99-fd05-43e4-a7f2-055be95b736e.png)
![image](https://user-images.githubusercontent.com/52731972/133088435-11d67fc4-d1af-472a-b1e4-cc86364be3e4.png)

**Comment by AbderrahimAl** [comment]
Hello @zchryy03 
Facebook doesn't allow gathering the data without using the API. So to solve this issue please try to change your IP Address, and then solve the checkpoint error.
