### ISSUE TITLE
how prevent from banned?

### ISSUE THREAD

**Issue by lordmen99** [AbderrahimAl/Facebook-Scraper#7]
its possible banned from facebook ? how prevent this?

**Comment by AbderrahimAl** [comment]
Hi @lordmen99,

Facebook has a policy against scraping tools. Additionally, they implemented a number of technical measures to detect and block scraping activity.

The good news is you don't get banned from Facebook directly. Usually, you get a checkpoint where you need to prove you are a human/ account owner. 

After getting this checkpoint and solving it, it is always good to change your IP address.

**Comment by lordmen99** [comment]
but still have bug, in find_element. need update latest chrome

**Comment by AbderrahimAl** [comment]
Could you please write the exact error you get?
In the script, we use `chromedriver_autoinstaller` which installs the appropriate chrome driver based on your chrome version.

**Comment by AbderrahimAl** [comment]
Hi @lordmen99, I'll close this issue since it's related to #2, if you have any related feedback, feel free to leave comments on that issue.
