### ISSUE TITLE
how to scrap informations from one username

### ISSUE THREAD

**Issue by ihabpalamino** [AbderrahimAl/Facebook-Scraper#8]
hello i am asking about if i want to scrape informations by username that the user will insert how to do it?

**Comment by AbderrahimAl** [comment]
Hi @ihabpalamino ,  In that case, you might want to add two lines to the script where you will ask the user to enter his/her Facebook username and password: 


```python

if __name__ == "__main__":
    username = input(str("Enter your FB username: ")) # FB username
    password = input(str("Enter you FB password: ")) # FB password
    posts_url = input(str("Enter Posts Url: "))
    scraper = Post_Scraper(posts_url)
    scraper.login(username, password) 

```
